import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { dbConnection } from "@/lib/database";
import Nav from '@/components/navbar/Nav'
import { auth } from "@/auth";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Dreamer",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConnection();
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {session && <Nav session={session}/>}
        <div className={`${session ? 'sm:ml-64 mt-14' : ''}`}>
          {children}
        </div>
      </body>
    </html>
  );
}
